version: '3.6'

services:
  web:
    build: ./
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - PARSER_JSON_LIMIT=${PARSER_JSON_LIMIT}
    ports:
      - "${HTTP_PORT}:3000"
    volumes:
      - ./:/robotBase
    networks:
      - robot-network
    working_dir: /robotBase
    command: sh -c "npm install && npm run build && cd dist && node server.js"
    container_name: web

networks:
  robot-network:
    driver: bridge
